### ISSUE TITLE
怎么转成vue组件？

### ISSUE THREAD

**Issue by hanjunqiang** [zhang7758/swiper-scale#1]
麻烦指导一下，谢谢

**Comment by hanjunqiang** [comment]
> 麻烦指导一下，谢谢

**Comment by zhang7758** [comment]
就正常写组件那样，把要用的代码，写进组件，js在index.html页面引入就可以了

**Comment by zhang7758** [comment]
就正常写组件那样，把要用的代码，写进组件，js在index.html页面引入就可以了

**Comment by zhang7758** [comment]
> 麻烦指导一下，谢谢

就正常写组件那样，把要用的代码，写进组件，js在index.html页面引入就可以了

**Comment by zhang7758** [comment]
> 麻烦指导一下，谢谢

就正常写组件那样，把要用的代码，写进组件，js在index.html页面引入就可以了
